// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPXqxjp1839KYyNhEx84Z6VItq9iHF7r8',
    appId: '1:889172391845:web:460830982edb6e3bb51a4c',
    messagingSenderId: '889172391845',
    projectId: 'uaspmobil',
    authDomain: 'uaspmobil.firebaseapp.com',
    storageBucket: 'uaspmobil.appspot.com',
    measurementId: 'G-Z3SPDQVQV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVgn0kIF2xPoVlZAXmNvMHWQYOvwX9SpI',
    appId: '1:889172391845:android:5a4c19fa6775fc2eb51a4c',
    messagingSenderId: '889172391845',
    projectId: 'uaspmobil',
    storageBucket: 'uaspmobil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPKkX72Uh5oKIwKhS2CGBh-xgLAyNeLZc',
    appId: '1:889172391845:ios:07684eb1d6ddb1c1b51a4c',
    messagingSenderId: '889172391845',
    projectId: 'uaspmobil',
    storageBucket: 'uaspmobil.appspot.com',
    iosBundleId: 'com.example.uaspmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPXqxjp1839KYyNhEx84Z6VItq9iHF7r8',
    appId: '1:889172391845:web:1edebc1a6f836c5bb51a4c',
    messagingSenderId: '889172391845',
    projectId: 'uaspmobil',
    authDomain: 'uaspmobil.firebaseapp.com',
    storageBucket: 'uaspmobil.appspot.com',
    measurementId: 'G-86RH8MLGM7',
  );
}
